# Texas Tow Trucks

We're going to scrape some [tow trucks in Texas](https://www.tdlr.texas.gov/tools_search/).

In [80]:
from bs4 import BeautifulSoup

# Part One: Building a company list

Search for businesses with the word **WRECK** in their names.

* **Tip:** Start by scraping the first page to a dataframe, then expand to a loop that combines all of the pages. Finally combine all of the dataframes with `pd.concat`.
* **Tip:** There are a lot of ways to do this, although raw `pd.read_html` with a URL won't work! Some approaches are playwright-driven, some use [curlconverter](https://curlconverter.com/), etc etc. I recommend using requests and BeautifulSoup.
* **Tip:** You can't just do a `try`/`except`, because even if you ask for page 99999 it will always give you the last page again! Watch out that you don't get stuck in an infinite loop!

In [86]:
import requests

cookies = {
    '_gid': 'GA1.2.120081628.1670242629',
    'ASPSESSIONIDQAWSSDQC': 'JGINJJLCCCHEAPFNLIOCADAK',
    '_ga': 'GA1.1.453843418.1670242629',
    '_ga_8C39DM76B2': 'GS1.1.1670247215.2.0.1670247223.0.0.0',
}

headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    # 'Cookie': '_gid=GA1.2.120081628.1670242629; ASPSESSIONIDQAWSSDQC=JGINJJLCCCHEAPFNLIOCADAK; _ga=GA1.1.453843418.1670242629; _ga_8C39DM76B2=GS1.1.1670247215.2.0.1670247223.0.0.0',
    'Referer': 'https://www.tdlr.texas.gov/tools_search/mccs_search_process.asp',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
    'sec-ch-ua': '"Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
}

params = {
    'page': '2',
    'stype': 'name',
    'ls_temp': 'wreck',
    'ls_carrier_type': 'COMPANY',
}

response = requests.get(
    'https://www.tdlr.texas.gov/tools_search/mccs_search_process.asp',
    params=params,
    cookies=cookies,
    headers=headers,
)

In [88]:
df = pd.read_html(response.text)
df[2]

,0,1,2,3,4,5
0,Customer,DBA Name,TDLR Number,City,State,Zip code
1,A & A WRECKER AND RECOVERY L.L.C.,NaN,0568645VSF,AUSTIN,TX,78722
2,A & A WRECKER AND RECOVERY L.L.C.,NaN,0653350VSF,AUSTIN,TX,78722
3,A & H WRECKER SERVICE LLC,A&H WRECKER SERVICE,006543241C,SOUTH HOUSTON,TX,77587
4,A & I WRECKER SERVICE,NaN,005266963C,HOUSTON,TX,77012
5,A & L WRECKER,NaN,006415434C,DEER PARK,TX,77536
6,A & M WRECKER SERVICE LLC,NaN,006490059C,ROSENBERG,TX,77471
7,A & M WRECKER SERVICE LLC,NaN,0649006VSF,ROSENBERG,TX,77471
8,A & R WRECKER SERVICE,NaN,0648812VSF,DONNA,TX,78537
9,A B C WRECKER SERVICE INC,NaN,0577127VSF,WACO,TX,76708
10,"A WRECKER SERVICE,LLC",A WRECKER SERVICE,006060211C,STAFFORD,TX,77477
11,A&P BROTHER'S WRECKER SERVICES INC,NaN,006560024C,RICHMOND,TX,77406
12,A&R WRECKER SERVICE,FELIPE HERNANDEZ III,006488096C,DONNA,TX,78537
13,"A-1 WRECKER SERVICE, LLC",NaN,006181060C,FORT WORTH,TX,76116
14,"A-1 WRECKER SERVICE, LLC.",NaN,0618108VSF,FORT WORTH,TX,76116
15,A-ACTION WRECKER SERVICE,NaN,005766702C,FORT WORTH,TX,76105
16,A. MARTINEZ WRECKER SERVICE LLC,NaN,006555161C,HOUSTON,TX,77023
17,A.S.A.P. WRECKER SERVICE INC,NaN,006239524C,EL PASO,TX,79932
18,A1 QUICK STAR WRECKER SERVICE,NaN,005629226C,SAN ANTONIO,TX,78219
19,AA WRECKER SERVICE,NaN,0536827VSF,FORT WORTH,TX,76148
20,AA WRECKER SERVICE,NaN,0000037359,FORT WORTH,TX,76148

In [90]:
pages = range(1,42)
len(pages)

41

In [91]:
df_list = []
for page in pages:
    
    cookies = {
    '_gid': 'GA1.2.120081628.1670242629',
    'ASPSESSIONIDQAWSSDQC': 'JGINJJLCCCHEAPFNLIOCADAK',
    '_ga': 'GA1.1.453843418.1670242629',
    '_ga_8C39DM76B2': 'GS1.1.1670247215.2.0.1670247223.0.0.0',
    }

    headers = {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'Accept-Language': 'en-US,en;q=0.9',
        'Connection': 'keep-alive',
        # 'Cookie': '_gid=GA1.2.120081628.1670242629; ASPSESSIONIDQAWSSDQC=JGINJJLCCCHEAPFNLIOCADAK; _ga=GA1.1.453843418.1670242629; _ga_8C39DM76B2=GS1.1.1670247215.2.0.1670247223.0.0.0',
        'Referer': 'https://www.tdlr.texas.gov/tools_search/mccs_search_process.asp',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'same-origin',
        'Sec-Fetch-User': '?1',
        'Upgrade-Insecure-Requests': '1',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
        'sec-ch-ua': '"Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
    }

    params = {
        'page': page,
        'stype': 'name',
        'ls_temp': 'wreck',
        'ls_carrier_type': 'COMPANY',
    }

    response = requests.get(
        'https://www.tdlr.texas.gov/tools_search/mccs_search_process.asp',
        params=params,
        cookies=cookies,
        headers=headers,
    )
    df = pd.read_html(response.text)
    table = df[2]
    df_list.append(table)
len(df_list)
df_list[0]

,0,1,2,3,4,5
0,Customer,DBA Name,TDLR Number,City,State,Zip code
1,1ST CHOICE WRECKER SERVICE,"1ST CHOICE PAINT & BODY, INC",006096604C (Insurance not applied !),TERRELL,TX,75160
2,1ST CHOICE WRECKER SERVICE,"1ST CHOICE PAINT & BODY, INC.",0612137VSF (Insurance not applied !),TERRELL,TX,75160
3,1ST CHOICE WRECKER SERVICE LLC,NaN,006529369C,SILSBEE,TX,77656
4,1ST CHOICE WRECKER SERVICE LLC,NaN,0652937VSF,SILSBEE,TX,77656
5,1ST CHOICE WRECKER SERVICE LLC,NaN,0655000VSF,SILSBEE,TX,77656
6,1STCHOICEWRECKERSERVICELLC,NaN,0654581VSF,SILSBEE,TX,77656
7,24 HOUR WRECKER SERVICE INC.,NaN,005052021C,LANCASTER,TX,75146
8,"24 HOUR WRECKER SERVICE, INC",NaN,0514204VSF,LANCASTER,TX,75146
9,24/7 WRECKER SERVICE LLC,NaN,006551087C,HARLINGEN,TX,78550
10,290 WRECKER SERVICE INC,HWY 290 WRECKER SERVICE,0656637VSF,HOCKLEY,TX,77447
11,"290 WRECKER SERVICE, INC.",HWY 290 WRECKER SERVICE,0657944VSF,HOCKLEY,TX,77447
12,"290 WRECKER SERVICE, INC.",HIGHWAY 290 WRECKER,0545753VSF,HOCKLEY,TX,77447
13,"290 WRECKER SERVICE, INC.",HIGHWAY 290 WRECKER,005697854C,HOCKLEY,TX,77447
14,"3 ACES WRECKER SERVICE, LLC",NaN,006576510C,WALLISVILLE,TX,77597
15,"3 ACES WRECKER SERVICE, LLC",NaN,0657711VSF,WALLISVILLE,TX,77597
16,"3 ACES WRECKER SERVICE, LLC",NaN,0657712VSF,WALLISVILLE,TX,77597
17,"3 ACES WRECKER SERVICE, LLC",NaN,0657713VSF,WALLISVILLE,TX,77597
18,A & A AUTO & WRECKER SERVICE,NaN,0000031VSF,EDINBURG,TX,78539
19,A & A AUTO & WRECKER SERVICE,NaN,0000039432,EDINBURG,TX,78542
20,A & A WRECKER,NaN,005683182C,AUSTIN,TX,78722

In [92]:
len(df_list)

41

In [93]:
df = pd.concat(df_list, ignore_index=True)
df

,0,1,2,3,4,5
0,Customer,DBA Name,TDLR Number,City,State,Zip code
1,1ST CHOICE WRECKER SERVICE,"1ST CHOICE PAINT & BODY, INC",006096604C (Insurance not applied !),TERRELL,TX,75160
2,1ST CHOICE WRECKER SERVICE,"1ST CHOICE PAINT & BODY, INC.",0612137VSF (Insurance not applied !),TERRELL,TX,75160
3,1ST CHOICE WRECKER SERVICE LLC,NaN,006529369C,SILSBEE,TX,77656
4,1ST CHOICE WRECKER SERVICE LLC,NaN,0652937VSF,SILSBEE,TX,77656
...,...,...,...,...,...,...
850,WRIGHT'S WRECKER SERVICE,NaN,005388553C,NASH,TX,75569
851,WRIGHT'S WRECKER SERVICE,NaN,0508198VSF,NASH,TX,75569
852,WRIGHT'S WRECKER SERVICE,NaN,0593304VSF,NASH,TX,75569
853,XTREME WRECKER SERVICES INC.,NaN,0650507VSF (Expired!),BARSTOW,TX,79719
854,"XTREME WRECKER SERVICES, INC",NaN,006504760C (Expired!),BARSTOW,TX,79719

### Cleanup

If you haven't already, rename the columns to be:
    
    * Customer
    * DBA Name
    * TDLR Number
    * City
    * State
    * Zip code

and remove all of the rows where the customer name is `Customer`.

In [94]:
df.rename({0: "Customer", 1: "DBA Name", 2: "TDLR Number", 3: "City", 4: "State", 5: "Zip code"}, axis='columns', inplace=True)

In [95]:
#df.drop(df.query("'Customer'=='Customer'").index)
df.drop(df[df.Customer == 'Customer'].index, inplace=True)
df

,Customer,DBA Name,TDLR Number,City,State,Zip code
1,1ST CHOICE WRECKER SERVICE,"1ST CHOICE PAINT & BODY, INC",006096604C (Insurance not applied !),TERRELL,TX,75160
2,1ST CHOICE WRECKER SERVICE,"1ST CHOICE PAINT & BODY, INC.",0612137VSF (Insurance not applied !),TERRELL,TX,75160
3,1ST CHOICE WRECKER SERVICE LLC,NaN,006529369C,SILSBEE,TX,77656
4,1ST CHOICE WRECKER SERVICE LLC,NaN,0652937VSF,SILSBEE,TX,77656
5,1ST CHOICE WRECKER SERVICE LLC,NaN,0655000VSF,SILSBEE,TX,77656
...,...,...,...,...,...,...
850,WRIGHT'S WRECKER SERVICE,NaN,005388553C,NASH,TX,75569
851,WRIGHT'S WRECKER SERVICE,NaN,0508198VSF,NASH,TX,75569
852,WRIGHT'S WRECKER SERVICE,NaN,0593304VSF,NASH,TX,75569
853,XTREME WRECKER SERVICES INC.,NaN,0650507VSF (Expired!),BARSTOW,TX,79719
854,"XTREME WRECKER SERVICES, INC",NaN,006504760C (Expired!),BARSTOW,TX,79719

## Save as `wreckers.csv`

In [96]:
df.to_csv('wreckers.csv', index=False)

In [ ]:
!ls

# Part Two: Company info

> You can use whatever tool you'd like for this, but remember that form submission doesn't necessarily mean Selenium/Playwright! If you want to go the `requests` route instead, it might mean anything from adding user-agent headers to using [curlconverter](https://curlconverter.com/) to steal the whole headers/cookies/form details. And the only way to know is trial-and-error!

## Step 1: Scraping one page

Try searching from the [tools page](https://www.tdlr.texas.gov/tools_search/) for the TDLR Number `006556161C`. From the results page, scrape the:

* Business name
* Phone number
* License status
* Physical address

And save the results into a dictionary. It's best if each item has its own key, but **it's fine to pull "larger" sections of the page and split them up in pandas later on**

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

In [ ]:
driver = webdriver.Chrome()

In [ ]:
driver.get('https://www.tdlr.texas.gov/tools_search/')

In [ ]:
tow_input = driver.find_element(By.XPATH, '//*[@id="mcrdata"]')
tow_input.send_keys("006556161C")

In [ ]:
search_button = driver.find_element(By.XPATH, '//*[@id="submit3"]')
search_button.click()

In [ ]:
biz_name = driver.find_element(By.XPATH, '//*[contains(text(), "Name")]/..')
biz_name.text.replace('Name:', "").strip()

In [ ]:
phone = driver.find_element(By.XPATH, "//*[contains(text(), 'Phone')]/..")
phone.text.replace('Phone:', "").strip()

In [ ]:
lic_status = driver.find_element(By.XPATH, "//*[contains(text(), 'Status')]/..")
lic_status.text.replace('Status:', '').strip()

In [ ]:
phys_add = driver.find_element(By.XPATH, "//*[contains(text(), 'Physical')]/..")
clean_add = phys_add.text.split(":")[-1].strip()
final_add = clean_add.replace('\n', ', ')
final_add

In [55]:
tow_info = {}
tow_info['biz_name'] = biz_name.text.replace('Name:', "").strip()
tow_info['phone'] = phone.text.replace('Phone:', "").strip()
tow_info['license_status'] = lic_status.text.replace('Status:', "").strip()
tow_info['physical_address'] = final_add
tow_info

{'biz_name': 'DIRTY SOUTH TRANSPORT AND RECOVERY, LLC',
 'phone': '713-259-5445',
 'license_status': 'Active',
 'physical_address': '11053 LORETTA LN, PLANTERSVILLE, TX. 77363'}

## Step 2: Converting to a function

Write a function called `get_tdlr_info` that is given a TDLR number and returns a dictionary with the business name, phone number, license status, and physical address. You'll mostly be able to use the same content as above.

Test with `0654479VSF`, and confirm that the information is in there. Did it not work out? Go back and edit your selectors, or be a little broader in the parts of the page you sweep up.

In [98]:
df['TDLR Number']

1      006096604C (Insurance not applied !)
2      0612137VSF (Insurance not applied !)
3                                006529369C
4                                0652937VSF
5                                0655000VSF
                       ...
850                              005388553C
851                              0508198VSF
852                              0593304VSF
853                   0650507VSF (Expired!)
854                   006504760C (Expired!)
Name: TDLR Number, Length: 814, dtype: object

In [105]:
def get_tdlr_info(row):
    driver = webdriver.Chrome()
    driver.get('https://www.tdlr.texas.gov/tools_search/')
    tow_input = driver.find_element(By.XPATH, '//*[@id="mcrdata"]')
    tow_input.send_keys(row['TDLR Number'])
    driver.find_element(By.XPATH, '//*[@id="submit3"]').click()
    
    biz_name = driver.find_element(By.XPATH, '//*[contains(text(), "Name")]/..')
    phone = driver.find_element(By.XPATH, "//*[contains(text(), 'Phone')]/..")
    lic_status = driver.find_element(By.XPATH, "//*[contains(text(), 'Status')]/..")
    phys_add = driver.find_element(By.XPATH, "//*[contains(text(), 'Physical')]/..")
    
    return pd.Series({
        'biz_name': biz_name.text.replace('Name:', "").strip(),
        'phone': phone.text.replace('Phone:', "").strip(),
        'license_status': lic_status.text.replace('Status:', "").strip(),
        'physical_address': phys_add.text.split(":")[-1].strip()
        
    })
wreckers_df = df.apply(get_tdlr_info, axis=1).join(df)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), "Name")]/.."}
  (Session info: chrome=107.0.5304.123)
Stacktrace:
Backtrace:
	Ordinal0 [0x009AACD3+2075859]
	Ordinal0 [0x0093EE61+1633889]
	Ordinal0 [0x0083B7BD+571325]
	Ordinal0 [0x0086AC2F+764975]
	Ordinal0 [0x0086AE1B+765467]
	Ordinal0 [0x0089D0F2+970994]
	Ordinal0 [0x00887364+881508]
	Ordinal0 [0x0089B56A+963946]
	Ordinal0 [0x00887136+880950]
	Ordinal0 [0x0085FEFD+720637]
	Ordinal0 [0x00860F3F+724799]
	GetHandleVerifier [0x00C5EED2+2769538]
	GetHandleVerifier [0x00C50D95+2711877]
	GetHandleVerifier [0x00A3A03A+521194]
	GetHandleVerifier [0x00A38DA0+516432]
	Ordinal0 [0x0094682C+1665068]
	Ordinal0 [0x0094B128+1683752]
	Ordinal0 [0x0094B215+1683989]
	Ordinal0 [0x00956484+1729668]
	BaseThreadInitThunk [0x75B8FEF9+25]
	RtlGetAppContainerNamedObjectPath [0x77527BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77527B8E+238]

In [ ]:
wreckers_df

## Step 3: Scraping many pages

Using pandas, read in `trucks-subset.csv`.

## Scrape every single row, creating a new dataframe from the scraped data.

You probably want to refer to the classwork about using `.apply`.

Right now, the results from `.apply` will be a list of dictionaries. You can either change your function to `return pd.Series(data)` to make it become a dataframe automatically, or convert the list of dictionaries you end up with to a dataframe using `pd.DataFrame`.

* **Tip:** If you're using Playwright to navigate pages... it's going to be a bit more difficult.
* **Tip:** Remember to use `join` and not `merge` to combine your dataframes

## Save your dataframe as `data-uncleaned.csv`

# Cleaning your data

## Re-open the `data-uncleaned.csv` file

You probably want to set `pd.options.display.max_colwidth`

## Clean it up!

Make sure there are columns for

- Business name
- Phone number
- License status
- Physical address

And drop all of the other columns (The easiest way is to use `df.drop(columns=[...])`)

# Putting it together

## Open up `wreckers.csv` from Part 1

## Clean up the TDLR Number column to *just* the TDLR number

## Applying 

Use `.apply` to run your scraping script on all of your TDLR numbers. Save the results into a new dataframe.

* **Tip:** You can also just do this for the first 20 or so if you don't like waiting around.

### Use `.join` to combine it with the original dataframe

### Save to a CSV